// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0
// source: copyfrom.go

package repo

import (
	"context"
)

// iteratorForPortfolioTriggers_Create implements pgx.CopyFromSource.
type iteratorForPortfolioTriggers_Create struct {
	rows                 []PortfolioTriggers_CreateParams
	skippedFirstNextCall bool
}

func (r *iteratorForPortfolioTriggers_Create) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForPortfolioTriggers_Create) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ID,
		r.rows[0].PortfolioID,
		r.rows[0].Type,
		r.rows[0].Currency,
		r.rows[0].Limit,
		r.rows[0].Percent,
		r.rows[0].TrailingAlert,
		r.rows[0].StartTotalCost,
		r.rows[0].CreatedAt,
	}, nil
}

func (r iteratorForPortfolioTriggers_Create) Err() error {
	return nil
}

func (q *Queries) PortfolioTriggers_Create(ctx context.Context, arg []PortfolioTriggers_CreateParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"portfolio_triggers"}, []string{"id", "portfolio_id", "type", "currency", "limit", "percent", "trailing_alert", "start_total_cost", "created_at"}, &iteratorForPortfolioTriggers_Create{rows: arg})
}
