// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0

package repo

import (
	"time"

	"github.com/google/uuid"
	"gitlab.com/moderntoken/gateways/decimal"
)

type Account struct {
	ID           int64
	Name         string
	ExchangeName string
	Key          string
	Secret       string
	Passphrase   *string
	Aliases      []string
}

type PortfolioTrigger struct {
	ID             uuid.UUID
	PortfolioID    int64
	Type           string
	Currency       string
	CreatedAt      time.Time
	Limit          *decimal.Decimal
	Percent        *decimal.Decimal
	TrailingAlert  bool
	StartTotalCost *decimal.Decimal
}
